# Generated by Django 3.2.8 on 2021-10-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211015_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='average_rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='ratings_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
