# Generated by Django 3.2.8 on 2021-10-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211015_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='api.Books'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='books',
            field=models.ManyToManyField(related_name='categories', to='api.Books'),
        ),
    ]
