# Generated by Django 3.2.8 on 2021-10-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211015_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='books',
            field=models.ManyToManyField(related_name='categories', to='api.Book', verbose_name='Books list'),
        ),
    ]
