# Generated by Django 3.2.8 on 2021-10-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211015_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='api.Book'),
        ),
        migrations.AddField(
            model_name='category',
            name='books',
            field=models.ManyToManyField(related_name='categories', to='api.Book', verbose_name='Books list'),
        ),
    ]
